export default [
    {
        languageOptions: {
            parserOptions: {
                ecmaVersion: 2024,
                sourceType: 'module'
            }
        },
        rules: {
            'no-await-in-loop': 'error',
            'no-console': 'warn',
            'no-extra-parens': ['error', 'all', { nestedBinaryExpressions: false }],
            'no-template-curly-in-string': 'error',
            'no-unexpected-multiline': 'error',
            curly: ['error', 'all'],
            eqeqeq: ['error', 'always', { null: 'ignore' }],
            'no-eval': 'error',
            'no-implicit-coercion': ['error', { boolean: false, number: true, string: true, allow: [] }],
            'no-multi-spaces': 'error',
            'no-new-wrappers': 'error',
            'no-return-assign': ['error', 'always'],
            'no-self-compare': 'error',
            'no-unused-expressions': ['error', { allowShortCircuit: true, allowTernary: true }],
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            yoda: ['error', 'never'],
            'no-delete-var': 'error',
            'no-label-var': 'error',
            'no-shadow-restricted-names': 'error',
            'no-undef-init': 'error',
            'no-use-before-define': ['error', { functions: true, classes: true, variables: true }],
            'array-bracket-spacing': ['error', 'never'],
            'block-spacing': ['error', 'always'],
            'brace-style': ['error', '1tbs', { allowSingleLine: true }],
            camelcase: ['error', { properties: 'never' }],
            'comma-dangle': ['error', 'never'],
            'comma-spacing': ['error', { before: false, after: true }],
            'comma-style': ['error', 'last'],
            'consistent-this': ['error', 'self'],
            'eol-last': ['error', 'always'],
            'func-call-spacing': ['error', 'never'],
            indent: ['error', 4, { SwitchCase: 2 }],
            'key-spacing': ['error', { beforeColon: false, afterColon: true }],
            'keyword-spacing': ['error', { before: true, after: true }],
            'linebreak-style': ['error', 'unix'],
            'new-cap': ['error', { newIsCap: true, capIsNew: false }],
            'new-parens': 'error',
            'no-array-constructor': 'error',
            'no-lonely-if': 'error',
            'no-mixed-spaces-and-tabs': 'error',
            'no-multiple-empty-lines': ['error', { max: 1 }],
            'no-nested-ternary': 'error',
            'no-new-object': 'error',
            'no-trailing-spaces': 'error',
            'no-whitespace-before-property': 'error',
            'object-curly-spacing': ['error', 'always'],
            'one-var': ['error', 'never'],
            'operator-linebreak': ['error', 'after'],
            'quote-props': ['error', 'as-needed'],
            quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
            semi: ['error', 'always'],
            'semi-spacing': ['error', { before: false, after: true }],
            'space-before-blocks': ['error', 'always'],
            'space-before-function-paren': ['error', 'never'],
            'space-in-parens': ['error', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': ['error', { words: true, nonwords: false }],
            'spaced-comment': ['error', 'always', { markers: ['global', 'eslint', 'eslint-disable', '*package', '!', ','] }],
            'arrow-spacing': ['error', { before: true, after: true }],
            'constructor-super': 'error',
            'no-class-assign': 'error',
            'no-const-assign': 'error',
            'no-dupe-class-members': 'error',
            'no-duplicate-imports': 'error',
            'no-new-symbol': 'error',
            'no-this-before-super': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-constructor': 'error',
            'no-useless-rename': ['error', {
                ignoreDestructuring: false,
                ignoreImport: false,
                ignoreExport: false
            }],
            'no-var': 'error',
            'object-shorthand': ['error', 'always', { avoidQuotes: true }],
            'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
            'prefer-const': ['error', { destructuring: 'all' }],
            'prefer-numeric-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            'require-yield': 'error',
            'rest-spread-spacing': ['error', 'never'],
            'symbol-description': 'error',
            'template-curly-spacing': ['error', 'never'],
            'yield-star-spacing': ['error', 'both']
        }
    }
];
